# Generated by Django 3.0.4 on 2020-03-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
